### ISSUE TITLE
Obsolete reference to GO111MODULE in paper/build/build_compilation.md

### ISSUE THREAD

**Issue by dwymi02** [hacash/paper#3]
In document [build_compilation.md], in section [Compile the go executables], there is the following sentence:

Note to set the GO111MODULE="auto" environment variable at compile time:
// compile NOTE: set go module env config
GO111MODULE="auto"

As documented in URL [https://go.dev/blog/go116-module-changes], the following is stated:

We plan to drop support for GOPATH mode in Go 1.17. In other words, Go 1.17 will ignore GO111MODULE.

Can I recommend that document be updated to state if compiling Hacash code utilizing Go LT 1.17, that the environment variable [GO111MODULE] can be used. But, if running Go 1.17 or higher, then do not use the environment variable GO111MODULE.

THANX(MKD).

**Comment by jojoin** [comment]
You can just modify this document by submitting a commit. thanks ^_^

**Comment by dwymi02** [comment]
Additionally, in the section [Compile the go executables], the document references building executables as [.exe] files. This is a Windows convention.

Document will be updated to remove the [.exe] extension ...

**Comment by dwymi02** [comment]
As per your request, I will update the document ...
